[tool.poetry]
name = "deepml-challenges-"
version = "0.1.0"
description = ""
authors = ["G0rg0ne <reda1999nox@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
